#ansible-playbook test-playbook.yml --extra-vars "ansible_become_pass=sudo_pass"
#To run without installing software dependencies
#ansible-playbook test-playbook.yml --extra-vars "ansible_become_pass=sudo_pass" --skip-tags "software"
- hosts: localhost

  pre_tasks:
     - raw:  ansible-galaxy role install -r requirements.yml

  vars:
    #create, destroy
    create_destroy: create
    #true, false
    renew: true
    #Name of the project this key will work for
    project: arsolute

  tasks:
    - name: Including role to test
      include_role:
        name: '../common_ansible-vault-key'
