- name: Ensure that key folder exists
  become: true
  file:
    path: "/{{ host_root_dir }}/{{ keys_dir }}"
    owner: "{{ ansible_user_id }}"
    state: directory
    recurse: yes
  when: create_destroy == "create"

- name: Let's {{ create_destroy }} key
  become: true
  file:
    path: "/{{ host_root_dir }}/{{ keys_dir }}/.vault-pass"
    state: absent
  when: create_destroy == "destroy" or renew == true

- name: Checking if a key already exist
  stat:
    path: "/{{ host_root_dir }}/{{ keys_dir }}/.vault-pass"
  register: vault_pass

#byxussof this needs ansible 2.8
#- name: Let's {{ create_destroy }} ssh-key encryption This tasks needs ansible 2.8
#  openssh_keypair:
#    path: "/{{ host_root_dir }}/{{ keys_dir }}/.vault-pass"
#  when: create_destroy == "create" and vault_pass is not defined and ansible_version.major >= 2 and ansible_version.minor >= 8


- name: Let's {{ create_destroy }} ssh-key encryption with shell
  command : 'ssh-keygen -q -t rsa -f /{{ host_root_dir }}/{{ keys_dir }}/.vault-pass -C "" -N ""'
  args:
    creates: '/{{ host_root_dir }}/{{ keys_dir }}/.vault-pass'
  when: create_destroy == "create" and vault_pass.stat.path is not defined

- name: Deleting autogenerated private-key
  file:
    path: "/{{ host_root_dir }}/{{ keys_dir }}/.vault-pass"
    state: absent
  when: create_destroy == "create" and vault_pass.stat.path is not defined

- name: Renaming
  shell: mv .vault-pass.pub .vault-pass
  args:
    chdir: "/{{ host_root_dir }}/{{ keys_dir }}/"
  when: create_destroy == "create" and vault_pass.stat.path is not defined
